apiVersion: v1
kind: Service
metadata:
  name: test-kubernetes
  labels:
    app: test-kubernetes
spec:
  ports:
    - port: 80
  selector:
    app: test-kubernetes
    tier: test-kubernetes
  type: LoadBalancer